version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    network_mode: bridge
    links:
      - socket-server
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
  socket-server:
    build: ./
    network_mode: bridge
    expose:
    #   - "8080"
      - "8081"
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true